In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
# 平方根を計算する
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [4]:
# 自然対数の底ｅの累乗
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [5]:
# 正規分布に従う乱数
A = np.random.randn(10)
A

array([-1.37902468,  0.97226754,  0.58038611, -0.12531737, -0.3379422 ,
        0.42983223, -0.67329458, -1.46500945,  2.18462539, -0.69545337])

In [6]:
# 別のアレイも用意
B = np.random.randn(10)
B

array([-0.36712267,  0.27459795,  0.99441127,  0.26979353, -2.7143163 ,
        0.38043638, -0.87285675, -0.27424963, -0.96872919, -0.09147413])

In [7]:
# 2つのアレイを足す
np.add(A, B)

array([-1.74614735,  1.24686548,  1.57479738,  0.14447616, -3.0522585 ,
        0.81026861, -1.54615133, -1.73925909,  1.2158962 , -0.7869275 ])

In [8]:
# 各要素の大きいほうを返す
np.maximum(A, B)

array([-0.36712267,  0.97226754,  0.99441127,  0.26979353, -0.3379422 ,
        0.42983223, -0.67329458, -0.27424963,  2.18462539, -0.09147413])

In [9]:
# この他の演算子に関しては、numpyのドキュメントに詳しい情報があります。
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"
import webbrowser
webbrowser.open(website)

True